const Features = () => {
  const features = [
    {
      title: "AI-Powered Plans",
      description: "Nutrition plans generated by advanced AI models based on your personal goals.",
      icon: "🤖"
    },
    {
      title: "Customizable",
      description: "Adjust your plans based on dietary preferences, allergies, and lifestyle.",
      icon: "⚙️"
    },
    {
      title: "Track Progress",
      description: "Monitor your nutrition and see how you're progressing toward your goals.",
      icon: "📈"
    },
    {
      title: "Expert Guidance",
      description: "Get recommendations from nutrition experts powered by AI insights.",
      icon: "👩‍⚕️"
    },
    {
      title: "Meal Planning",
      description: "Plan your meals for the week with our AI-powered meal planner.",
      icon: "🍽️"
    },
    {
      title: "Recipe Discovery",
      description: "Discover new recipes tailored to your dietary needs and preferences.",
      icon: " cookbook"
    }
  ];

  return (
    <div className="py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-white dark:text-white mb-4">
            Why Choose Our <span className="bg-gradient-to-r from-blue-400 to-purple-500 bg-clip-text text-transparent">AI Nutritionist</span>
          </h2>
          <p className="text-xl text-gray-300 dark:text-gray-300 max-w-3xl mx-auto">
            Our platform combines cutting-edge AI technology with nutritional science to provide you with personalized plans
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <div 
              key={index}
              className="bg-white/10 dark:bg-gray-800/30 backdrop-blur-md p-6 rounded-xl border border-white/20 dark:border-gray-700 text-center transition-all duration-300 hover:scale-105 hover:animate-card-hover group"
            >
              <div className="text-4xl mb-4 group-hover:scale-110 transition-transform duration-300">{feature.icon}</div>
              <h3 className="text-xl font-bold text-white dark:text-white mb-4 group-hover:text-blue-400 transition-colors duration-300">
                {feature.title}
              </h3>
              <p className="text-gray-300 dark:text-gray-300">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Features;