import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

const Hero = () => {
  const [isVisible, setIsVisible] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    setIsVisible(true);
  }, []);

  return (
    <div className="max-w-7xl mx-auto text-center relative">
      {/* Animated background elements */}
      <div className="absolute top-0 left-0 w-full h-full overflow-hidden -z-10">
        <div className="absolute top-1/4 left-1/4 w-64 h-64 bg-purple-500/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-1/3 right-1/4 w-72 h-72 bg-blue-500/10 rounded-full blur-3xl animate-pulse delay-1000"></div>
        <div className="absolute top-1/3 right-1/3 w-56 h-56 bg-pink-500/10 rounded-full blur-3xl animate-pulse delay-2000"></div>
      </div>
      
      <div className={`transition-all duration-1000 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
        <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold text-white dark:text-white mb-6 leading-tight">
          <span className="bg-gradient-to-r from-blue-400 via-purple-500 to-pink-500 bg-clip-text text-transparent inline-block animate-text-glow">
            Personalized AI Nutrition Plans
          </span>
        </h1>
        <p className="text-xl text-gray-300 dark:text-gray-300 mb-8 max-w-3xl mx-auto transition-all duration-700 delay-300 opacity-0 animate-fade-in">
          Get science-backed, personalized meal plans generated by AI tailored to your goals, preferences, and dietary needs.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center transition-all duration-700 delay-500 opacity-0 animate-fade-in">
          <button 
            onClick={() => navigate('/register')}
            className="bg-gradient-to-r from-blue-500 to-purple-600 text-white px-8 py-4 rounded-xl text-lg font-medium transition-all duration-300 hover:scale-105 transform hover:shadow-xl hover:shadow-blue-500/30 hover:shadow-lg animate-button-float"
          >
            Get Started
          </button>
          <button 
            onClick={() => navigate('/login')}
            className="bg-white/10 dark:bg-gray-800/50 backdrop-blur-md text-white dark:text-white px-8 py-4 rounded-xl text-lg font-medium transition-all duration-300 hover:scale-105 transform border border-white/30 dark:border-gray-600 hover:border-white/50 dark:hover:border-gray-500 animate-button-float delay-200"
          >
            Learn More
          </button>
        </div>
      </div>
      
      {/* Animated floating elements */}
      <div className="mt-16 relative max-w-4xl mx-auto">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
          <div className="bg-white/10 dark:bg-gray-800/30 backdrop-blur-md p-6 rounded-xl border border-white/20 dark:border-gray-700 text-center transition-all duration-500 hover:scale-110 animate-float delay-300">
            <div className="text-3xl font-bold text-white dark:text-white mb-2">98%</div>
            <p className="text-gray-300 dark:text-gray-300 text-sm">Satisfaction Rate</p>
          </div>
          <div className="bg-white/10 dark:bg-gray-800/30 backdrop-blur-md p-6 rounded-xl border border-white/20 dark:border-gray-700 text-center transition-all duration-500 hover:scale-110 animate-float delay-500">
            <div className="text-3xl font-bold text-white dark:text-white mb-2">24/7</div>
            <p className="text-gray-300 dark:text-gray-300 text-sm">AI Support</p>
          </div>
          <div className="bg-white/10 dark:bg-gray-800/30 backdrop-blur-md p-6 rounded-xl border border-white/20 dark:border-gray-700 text-center transition-all duration-500 hover:scale-110 animate-float delay-700">
            <div className="text-3xl font-bold text-white dark:text-white mb-2">500+</div>
            <p className="text-gray-300 dark:text-gray-300 text-sm">Recipes</p>
          </div>
          <div className="bg-white/10 dark:bg-gray-800/30 backdrop-blur-md p-6 rounded-xl border border-white/20 dark:border-gray-700 text-center transition-all duration-500 hover:scale-110 animate-float delay-900">
            <div className="text-3xl font-bold text-white dark:text-white mb-2">10K+</div>
            <p className="text-gray-300 dark:text-gray-300 text-sm">Happy Users</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Hero;