import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';

const Hero = () => {
  const [isVisible, setIsVisible] = useState(false);
  const [scrollY, setScrollY] = useState(0);
  const navigate = useNavigate();

  useEffect(() => {
    setIsVisible(true);
    
    const handleScroll = () => setScrollY(window.scrollY);
    window.addEventListener('scroll', handleScroll);
    
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  return (
    <div className="max-w-7xl mx-auto text-center relative overflow-hidden">
      {/* Animated background elements */}
      <div className="absolute inset-0 overflow-hidden -z-10">
        <div 
          className="absolute top-1/4 left-1/4 w-64 h-64 bg-gradient-to-r from-purple-500/20 to-pink-500/20 rounded-full blur-3xl animate-pulse"
          style={{ transform: `translateY(${scrollY * 0.1}px)` }}
        ></div>
        <div 
          className="absolute bottom-1/3 right-1/4 w-72 h-72 bg-gradient-to-r from-blue-500/20 to-purple-500/20 rounded-full blur-3xl animate-pulse delay-1000"
          style={{ transform: `translateY(${scrollY * -0.05}px)` }}
        ></div>
        <div 
          className="absolute top-1/3 right-1/3 w-56 h-56 bg-gradient-to-r from-pink-500/20 to-blue-500/20 rounded-full blur-3xl animate-pulse delay-2000"
          style={{ transform: `translateY(${scrollY * 0.08}px)` }}
        ></div>
        
        {/* Additional animated shapes */}
        <div className="absolute top-1/2 left-1/2 w-96 h-96 bg-gradient-to-r from-blue-500/10 to-purple-500/10 rounded-full blur-3xl animate-ping opacity-20"></div>
      </div>
      
      <div className={`transition-all duration-1000 ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}>
        <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold text-white dark:text-white mb-6 leading-tight relative">
          <span className="bg-gradient-to-r from-blue-400 via-purple-500 to-pink-500 bg-clip-text text-transparent inline-block animate-text-glow">
            Personalized AI Nutrition Plans
          </span>
          <span className="absolute -bottom-2 left-0 w-full h-1 bg-gradient-to-r from-transparent via-blue-500 to-transparent opacity-50 transform scale-x-0 hover:scale-x-100 transition-transform duration-700 origin-left"></span>
        </h1>
        <p className="text-xl text-gray-300 dark:text-gray-300 mb-8 max-w-3xl mx-auto transition-all duration-700 delay-300 opacity-0 animate-fade-in">
          Get science-backed, personalized meal plans generated by AI tailored to your goals, preferences, and dietary needs.
        </p>
        <div className="flex flex-col sm:flex-row gap-6 justify-center transition-all duration-700 delay-500 opacity-0 animate-fade-in">
          <button 
            onClick={() => navigate('/register')}
            className="group relative bg-gradient-to-r from-blue-500 to-purple-600 text-white px-8 py-4 rounded-xl text-lg font-medium transition-all duration-300 hover:scale-105 transform hover:shadow-2xl hover:shadow-blue-500/30 overflow-hidden"
          >
            <span className="relative z-10">Get Started</span>
            <div className="absolute inset-0 bg-gradient-to-r from-purple-600 to-pink-600 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
            <div className="absolute inset-0 bg-white/20 transform scale-x-0 group-hover:scale-x-100 transition-transform duration-500 origin-left"></div>
          </button>
          <button 
            onClick={() => navigate('/login')}
            className="group relative bg-white/10 dark:bg-gray-800/50 backdrop-blur-md text-white dark:text-white px-8 py-4 rounded-xl text-lg font-medium transition-all duration-300 hover:scale-105 transform border border-white/30 dark:border-gray-600 hover:border-white/50 dark:hover:border-gray-500 overflow-hidden"
          >
            <span className="relative z-10">Learn More</span>
            <div className="absolute inset-0 bg-gradient-to-r from-blue-500/20 to-purple-500/20 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
            <div className="absolute inset-0 bg-white/10 transform scale-x-0 group-hover:scale-x-100 transition-transform duration-500 origin-left"></div>
          </button>
        </div>
      </div>
      
      {/* Animated floating elements */}
      <div className="mt-16 relative max-w-4xl mx-auto">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
          {[
            { value: '98%', label: 'Satisfaction Rate', delay: 'delay-300' },
            { value: '24/7', label: 'AI Support', delay: 'delay-500' },
            { value: '500+', label: 'Recipes', delay: 'delay-700' },
            { value: '10K+', label: 'Happy Users', delay: 'delay-900' }
          ].map((stat, index) => (
            <div 
              key={index}
              className={`bg-white/10 dark:bg-gray-800/30 backdrop-blur-md p-6 rounded-xl border border-white/20 dark:border-gray-700 text-center transition-all duration-500 hover:scale-110 animate-float ${stat.delay}`}
            >
              <div className="text-3xl font-bold text-white dark:text-white mb-2 transform transition-transform duration-300 group-hover:scale-110">
                {stat.value}
              </div>
              <p className="text-gray-300 dark:text-gray-300 text-sm transition-colors duration-300 group-hover:text-blue-300">
                {stat.label}
              </p>
              <div className="mt-2 h-0.5 bg-gradient-to-r from-transparent via-blue-500 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
            </div>
          ))}
        </div>
      </div>
      
      {/* Animated wave element */}
      <div className="mt-20 relative">
        <div className="absolute -bottom-10 left-0 right-0 h-20 overflow-hidden">
          <div className="absolute bottom-0 left-0 w-full h-4 bg-gradient-to-r from-blue-500/20 via-purple-500/20 to-pink-500/20 animate-wave"></div>
        </div>
      </div>
    </div>
  );
};

export default Hero;