import { useState } from 'react';
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import Navbar from './components/Navbar';
import './App.css';

function App() {
  return (
    <Router>
      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-blue-900 to-purple-900 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
        <Navbar />
        
        {/* Hero Section */}
        <div className="pt-24 pb-12 px-4 sm:px-6 lg:px-8">
          <div className="max-w-7xl mx-auto text-center">
            <h1 className="text-4xl md:text-6xl font-bold text-white dark:text-white mb-6">
              <span className="bg-gradient-to-r from-blue-400 via-purple-500 to-pink-500 bg-clip-text text-transparent">
                Personalized AI Nutrition Plans
              </span>
            </h1>
            <p className="text-xl text-gray-300 dark:text-gray-300 mb-8 max-w-3xl mx-auto">
              Get science-backed, personalized meal plans generated by AI tailored to your goals, preferences, and dietary needs.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button className="bg-gradient-to-r from-blue-500 to-purple-600 text-white px-8 py-3 rounded-lg text-lg font-medium transition-all duration-300 hover:scale-105 transform hover:shadow-lg hover:shadow-blue-500/25">
                Get Started
              </button>
              <button className="bg-white/10 dark:bg-gray-800/50 backdrop-blur-md text-white dark:text-white px-8 py-3 rounded-lg text-lg font-medium transition-all duration-300 hover:scale-105 transform border border-white/30 dark:border-gray-600 hover:border-white/50 dark:hover:border-gray-500">
                Learn More
              </button>
            </div>
          </div>
        </div>
        
        {/* Features Section */}
        <div className="py-12 px-4 sm:px-6 lg:px-8">
          <div className="max-w-7xl mx-auto">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              <div className="bg-white/10 dark:bg-gray-800/30 backdrop-blur-md p-6 rounded-xl border border-white/20 dark:border-gray-700 text-center transition-all duration-300 hover:scale-105">
                <h3 className="text-xl font-bold text-white dark:text-white mb-4">AI-Powered Plans</h3>
                <p className="text-gray-300 dark:text-gray-300">Nutrition plans generated by advanced AI models based on your personal goals.</p>
              </div>
              <div className="bg-white/10 dark:bg-gray-800/30 backdrop-blur-md p-6 rounded-xl border border-white/20 dark:border-gray-700 text-center transition-all duration-300 hover:scale-105">
                <h3 className="text-xl font-bold text-white dark:text-white mb-4">Customizable</h3>
                <p className="text-gray-300 dark:text-gray-300">Adjust your plans based on dietary preferences, allergies, and lifestyle.</p>
              </div>
              <div className="bg-white/10 dark:bg-gray-800/30 backdrop-blur-md p-6 rounded-xl border border-white/20 dark:border-gray-700 text-center transition-all duration-300 hover:scale-105">
                <h3 className="text-xl font-bold text-white dark:text-white mb-4">Track Progress</h3>
                <p className="text-gray-300 dark:text-gray-300">Monitor your nutrition and see how you're progressing toward your goals.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Router>
  );
}

export default App
